# Generated by Django 4.2.2 on 2023-06-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
